"""Public API for reusable optional learner checkpoints."""

from .catalog import (
    CHECKPOINTS,
    DEFAULT_CHECKPOINT_ID,
    WEEK_01,
    CheckpointDefinition,
    UnknownCheckpointError,
    get_checkpoint,
)
from .core import (
    BASE_LABEL,
    CHECKPOINT_ID_SECTION,
    CHECKPOINT_SECTION,
    CODENAME_SECTION,
    HONOR_CONFIRMATION,
    HONOR_SECTION,
    ISSUE_TEMPLATE_FILENAME,
    NEEDS_FIX_LABEL,
    PASSED_LABEL,
    STATUS_COMMENT_MARKER,
    build_issue_form_url,
    codename_seed,
    generate_codename,
    is_status_comment,
    normalize_github_username,
    parse_codename_phrase,
    parse_issue_sections,
    parse_issue_submission,
    validate_issue_submission,
)

ACHIEVEMENT_MESSAGE = WEEK_01.achievement_message

__all__ = (
    "ACHIEVEMENT_MESSAGE",
    "BASE_LABEL",
    "CHECKPOINTS",
    "CHECKPOINT_ID_SECTION",
    "CHECKPOINT_SECTION",
    "CODENAME_SECTION",
    "DEFAULT_CHECKPOINT_ID",
    "HONOR_CONFIRMATION",
    "HONOR_SECTION",
    "ISSUE_TEMPLATE_FILENAME",
    "NEEDS_FIX_LABEL",
    "PASSED_LABEL",
    "STATUS_COMMENT_MARKER",
    "WEEK_01",
    "CheckpointDefinition",
    "UnknownCheckpointError",
    "build_issue_form_url",
    "codename_seed",
    "generate_codename",
    "get_checkpoint",
    "is_status_comment",
    "normalize_github_username",
    "parse_codename_phrase",
    "parse_issue_sections",
    "parse_issue_submission",
    "validate_issue_submission",
)
